# Configs the mapping of joints with real devices
# Define the different types of interfaces
types: [ gazebo_position, standard ]

groups: {  
 ptu1: { name: ptu1, type: standard, joints: [ptu1_joint_1, ptu1_joint_2], command_topic: /robotnik_ptu_node/in/joint_commands},
 ptu2: { name: ptu2, type: standard, joints: [ptu2_joint_1, ptu2_joint_2], command_topic: /robotnik_ptu_node/in/joint_commands},
 ptu: { name: ptu, type: standard, joints: [ptu1_joint_1, ptu1_joint_2, ptu2_joint_1, ptu2_joint_2], command_topic: /robotnik_ptu_node/in/joint_commands}
 #torso_head: { name: torso_head, type: standard, joints: [j1_torso, j1_head, j2_head], command_topic: /joint_commands}
 #base
}
