ptu1_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: ptu1_joint_1
    joint_speed: 0.25
    motor:
        id: 1
        init: 2048
        min:  0
        max:  4095

ptu1_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: ptu1_joint_2
    joint_speed: 0.25
    motor:
        id: 2
        init: 2048
        min: 0
        max: 4095

ptu2_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: ptu2_joint_1
    joint_speed: 0.25
    motor:
        id: 3
        init: 2048
        min:  0
        max:  4095

ptu2_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: ptu2_joint_2
    joint_speed: 0.25
    motor:
        id: 4
        init: 2048
        min: 0
        max: 4095


  
